// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf8lCTNHVDQs5C4psZYDyORjoklehoNfk',
    appId: '1:1083429575776:web:bd9ee0066e1fa26b24b705',
    messagingSenderId: '1083429575776',
    projectId: 'work-ws',
    authDomain: 'work-ws.firebaseapp.com',
    storageBucket: 'work-ws.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuddlIy29uRoTTA_iKUJ0DV-001WifC_Q',
    appId: '1:1083429575776:android:739e0ac59eddc8de24b705',
    messagingSenderId: '1083429575776',
    projectId: 'work-ws',
    storageBucket: 'work-ws.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2sMxQuXKFcvZVK4PVFulRCrBE3ZNJUI',
    appId: '1:1083429575776:ios:22f11a78becb42a624b705',
    messagingSenderId: '1083429575776',
    projectId: 'work-ws',
    storageBucket: 'work-ws.firebasestorage.app',
    iosBundleId: 'com.mta.emtc.worksyncFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2sMxQuXKFcvZVK4PVFulRCrBE3ZNJUI',
    appId: '1:1083429575776:ios:22f11a78becb42a624b705',
    messagingSenderId: '1083429575776',
    projectId: 'work-ws',
    storageBucket: 'work-ws.firebasestorage.app',
    iosBundleId: 'com.mta.emtc.worksyncFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf8lCTNHVDQs5C4psZYDyORjoklehoNfk',
    appId: '1:1083429575776:web:dc66e56ddd508b2124b705',
    messagingSenderId: '1083429575776',
    projectId: 'work-ws',
    authDomain: 'work-ws.firebaseapp.com',
    storageBucket: 'work-ws.firebasestorage.app',
  );
}
